kind: pipeline
name: default

steps:
- name: Build and Test
  image: golang:1.19
  commands:
  - go mod download
  - go build ./cmd/TraefikAccessControl
  - go test ./...

- name: push-public-registry
  image: plugins/docker
  settings:
    repo: ghcr.io/mheidinger/traefik-access-control
    registry: ghcr.io
    tags:
      - latest
      - ${DRONE_TAG}
    username:
      from_secret: github_username
    password:
      from_secret: github_password
  when:
    event:
    - tag
